// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gewgtujzynsazupmsbui.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdld2d0dWp6eW5zYXp1cG1zYnVpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk0NDY1MzYsImV4cCI6MjA2NTAyMjUzNn0.DUsoF5mVK2ofzrLbKBNNb_SzQDFr9EPEVSpQ5prOoHw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);